# Build status located at https://travis-ci.org/citra-emu/citra-web

# set-up-ssh is provided by travis-scripts.
# Setting up the SSH key for Github is described here.
# https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md

language: node_js
node_js: node
cache: yarn

script:
  - echo '========== Installing gulp & dependencies =========='
  - sudo apt-get install graphicsmagick
  - yarn global add hugo-bin
  - yarn global add gulp
  - yarn install

  - echo '========== Starting gulp deploy task =========='
  - hugo version
  - gulp all --production

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: build
 repo: CitraBotWeb/CitraBotWeb.github.io
 target_branch: master
 fqdn: citra-emu.org
 on:
   branch: master

notifications:
  email:
    - mods@citra-emu.org
