baseurl = "https://citra-emu.org/"
languageCode = "en-us"
theme = "citra-bs-theme"

# Define how many objects appear per pagination.
paginate = 10

[Languages]
  [Languages.en]
    title = "Citra"
    description = "Citra is an open-source emulator for the Nintendo 3DS capable of playing many of your favorite 3DS games."
    weight = 1

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "JSON" ]
