name = "Citra Bootstrap"
license = "GPLv3"
licenselink = ""
description = "Citra Official Theme"
homepage = "https://citra-emu.org/"
tags = []
features = ["", ""]
min_version = 0.16

[author]
  name = "flamesage"
  homepage = "https://citra-emu.org"
